#############################################################                                                          #
# Authors: zhangcheng                    #                                            #
#############################################################

dlo:
  use_first_frame: false

  odomNode:

    initialPose:
      use: false
      position:
        x: 0.0
        y: 0.0
        z: 0.0
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0

    preprocessing:
      cropBoxFilter:
        use: true
        size: 1.0
      voxelFilter:
        scan:
          use: false
          res: 0.1
        submap:
          use: false
          res: 0.1

    keyframe:
      threshD: 2
      threshR: 15

    submap:
      keyframe:
        knn: 10
        kcv: 10
        kcc: 10

    imu:
      calibTime: 3
      bufferSize: 2000

    gicp:
      minNumPoints: 10
      s2s:
        kCorrespondences: 10
        maxCorrespondenceDistance: 1.0
        maxIterations: 320
        transformationEpsilon: 0.000001
        euclideanFitnessEpsilon: 0.000001
        ransac:
          iterations: 5
          outlierRejectionThresh: 1.0
      s2m:
        kCorrespondences: 20
        maxCorrespondenceDistance: 0.5
        maxIterations: 320
        transformationEpsilon: 0.000001
        euclideanFitnessEpsilon: 0.000001
        ransac:
          iterations: 5
          outlierRejectionThresh: 1.0
